export const Posts = [
    {
      id:1,
      title:"ballon D'or Winnners 2021",
      slug:"ballon-d'or-winnners-2021",
      image:"https://c4.wallpaperflare.com/wallpaper/792/802/540/cristiano-ronaldo-real-madrid-ballon-d-or-wallpaper-preview.jpg",
      author:"Emily Smith",
      isFeatured:false,
      tag:"Sports",
      published_at: "2022-11-26",
    },
    {
      id:2,
      title:"Whats new in Laravel 8",
      slug:"whats-new-in-laravel-8",
      image:"https://c4.wallpaperflare.com/wallpaper/801/330/425/laravel-php-code-simple-wallpaper-preview.jpg",
      author:"Mccalister Nicolaus",
      isFeatured:true,
      tag:"Tech",
      published_at: "2022-01-26",
    },
    {
      id:3,
      title:"Billboard top 100 songs",
      slug:"billboard-top-100-songs",
      image:"https://i1.sndcdn.com/artworks-000899207863-m5drju-t500x500.jpg",
      author:"James Mcgee",
      isFeatured:false,
      tag:"Music",
      published_at: "2022-02-26",
    },
    {
      id:4,
      title:"Spiderman No Way Home Review",
      slug:"spiderman-no-way-home-review",
      image:"https://c4.wallpaperflare.com/wallpaper/763/710/546/spiderman-no-way-home-spiderverse-superhero-movies-digital-hd-wallpaper-preview.jpg",
      author:"Sarah Logan",
      isFeatured:true,
      tag:"Cinema",
      published_at: "2022-03-26",
    },
    {
      id:5,
      title:"Uefa fixtures 2022",
      slug:"uefa-fixtures-2022",
      image:"https://c4.wallpaperflare.com/wallpaper/426/395/739/champions-league-uefa-soccer-wallpaper-preview.jpg",
      author:"Emily Smith",
      isFeatured:false,
      tag:"Sports",
      published_at: "2022-04-26",
    },
    {
      id:6,
      title:"Svelte Upcoming Best JS Framework",
      slug:"svelte-upcoming-best-js-framework",
      image:"https://valuelogic.one/blog/wp-content/uploads/2020/11/Svelte-blogpost.png",
      author:"Mccalister Nicolaus",
      isFeatured:false,
      tag:"Tech",
      published_at: "2022-05-26",
    },
    {
      id:7,
      title:"BTS sold out Wembley",
      slug:"BTS-sold-out-wembley",
      image:"https://c4.wallpaperflare.com/wallpaper/229/551/811/bts-fake-j-hope-jimin-wallpaper-preview.jpg",
      author:"James Mcgee",
      isFeatured:false,
      tag:"Music",
      published_at: "2022-06-26",
    },
    {
      id:8,
      title:"Top 10 Netflix series to watch 2022",
      slug:"top-10-netflix-series-to-watch-2022",
      image:"https://www.notebookcheck.net/fileadmin/Notebooks/News/_nc3/A9DF1171_458C_4D7B_A253_573AF2ED7CB6.png",
      author:"Jackson Salamakes",
      isFeatured:false,
      tag:"Cinema",
      published_at: "2022-07-16",
    },
    {
      id:9,
      title:"Should EPL be Postponed?",
      slug:"should-EPL-be-postponed?",
      image:"https://assets.turbologo.com/blog/en/2020/01/19084653/Premier-League-symbol.png",
      author:"Emily Smith",
      isFeatured:false,
      tag:"Sports",
      published_at: "2022-01-12",
    },
    {
      id:10,
      title:"Why you should learn Ruby 2022",
      slug:"why-you-should-learn-ruby-2022",
      image:"https://www.pngitem.com/pimgs/m/12-120179_best-free-ruby-png-ruby-programming-language-logo.png",
      author:"Mccalister Nicolaus",
      isFeatured:false,
      tag:"Tech",
      published_at: "2022-04-11",
    },
    {
      id:11,
      title:"BET Awards 2022 results",
      slug:"BET-awards-2022-results",
      image:"https://www.kindpng.com/picc/m/490-4901925_bet-awards-logo-transparent-hd-png-download.png",
      author:"James Mcgee",
      isFeatured:false,
      tag:"Music",
      published_at: "2022-12-26",
    },
    {
      id:12,
      title:"Dune 2 Review",
      slug:"dune-2-review",
      image:"https://c4.wallpaperflare.com/wallpaper/792/423/674/dune-series-dunes-desert-tv-series-science-fiction-hd-wallpaper-preview.jpg",
      author:"Jackson Salamakes",
      isFeatured:false,
      tag:"Cinema",
      published_at: "2023-12-31",
    },
    {
      id:13,
      title:"Can Xavi Revive Barcelona?",
      slug:"can-xavi-revive-barcelona?",
      image:"https://c4.wallpaperflare.com/wallpaper/837/385/136/barcelona-fc-barcelona-stadium-camp-nou-wallpaper-preview.jpg",
      author:"Emily Smith",
      isFeatured:true,
      tag:"Sports",
      published_at: "2022-03-19",
    },
    {
      id:14,
      title:"JS Array methods every developer must know",
      slug:"js-array-methods-every-developer-must-know",
      image:"https://c4.wallpaperflare.com/wallpaper/562/372/1012/programmers-javascript-minimalism-wallpaper-preview.jpg",
      author:"Mccalister Nicolaus",
      isFeatured:false,
      tag:"Tech",
      published_at: "2022-08-12",
    },
    {
      id:15,
      title:"Ten songs you must listen on Spotify 2022",
      slug:"ten-songs-you-must-listen-on-spotify-2022",
      image:"https://c4.wallpaperflare.com/wallpaper/418/665/208/music-green-minimalism-logo-wallpaper-preview.jpg",
      author:"James Mcgee",
      isFeatured:false,
      tag:"Music",
      published_at: "2022-09-10",
    },
    {
      id:16,
      title:"Who should be the next James Bond?",
      slug:"who-should-be-the-next-james-bond?",
      image:"https://c4.wallpaperflare.com/wallpaper/566/384/903/james-bond-skyfall-film-stills-movies-wallpaper-preview.jpg",
      author:"Jackson Salamakes",
      isFeatured:true,
      tag:"Cinema",
      published_at: "2022-01-31",
    },
]